[package]
name = "wasm_offload_example"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm_offload = { version = "0.1.0", path = "../wasm_offload" }
wasm_offload_wasmtime = { version = "0.1.0", path = "../wasm_offload_wasmtime" }
